apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-templates
  namespace: monitoring
data:
  default.tmpl: |
    {{ define "slack.title" -}}
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}]
      {{ .GroupLabels.SortedPairs.Values | join " " }}
      {{ if gt (len .CommonLabels) (len .GroupLabels) -}}
        ({{ with .CommonLabels.Remove .GroupLabels.Names }}{{ .Values | join " " }}{{ end }})
      {{- end }}
    {{- end }}

    {{ define "slack.text" -}}
      {{ range .Alerts -}}
        *Alert:* {{ .Annotations.summary }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
        *Description:* {{ .Annotations.description }}
        *Namespace:* {{ .Labels.namespace }}
        *Started:* {{ .StartsAt | since }}
      {{ end }}
    {{- end }}
