apiVersion: v1
kind: Service
metadata:
  name: saas-backend-service
  namespace: backend
spec:
  selector:
    app: saas-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
