apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  password: "9512"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  jwt-secret: "supersecret123"
  mail-pass: "yadlmqaplhdtyqek"
  google-client-secret: "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"
  github-client-secret: "20042e49443011f83d29598c9a2f88e44d331622"
  gemini-api-key: "AIzaSyB7Wjoug0QSyzYWdIuwwubzcyyvppRgOgo"
